CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150122_InitialCreateV3') THEN
    CREATE TABLE "FlowEntries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ClusterName" text NOT NULL,
        "DstOwner" text NOT NULL,
        "DstNs" text NOT NULL,
        "SrcOwner" text NOT NULL,
        "SrcNs" text NOT NULL,
        "DstPort" integer NOT NULL,
        "TcpFlags" integer NOT NULL,
        "Time" bigint NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FlowEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150122_InitialCreateV3') THEN
    CREATE TABLE "PossibleDropEntries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ClusterName" text NOT NULL,
        "DstOwner" text NOT NULL,
        "DstNs" text NOT NULL,
        "SrcOwner" text NOT NULL,
        "SrcNs" text NOT NULL,
        "DstPort" integer NOT NULL,
        "Time" bigint NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PossibleDropEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150122_InitialCreateV3') THEN
    CREATE TABLE "RadarCollections" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "Owner" text NOT NULL,
        "NamespacesJson" text NOT NULL,
        "LabelsJson" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RadarCollections" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150122_InitialCreateV3') THEN
    CREATE TABLE "RedundantFlowEntries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ClusterName" text NOT NULL,
        "DstOwner" text NOT NULL,
        "DstNs" text NOT NULL,
        "SrcOwner" text NOT NULL,
        "SrcNs" text NOT NULL,
        "DstPort" integer NOT NULL,
        "TcpFlags" integer NOT NULL,
        "Time" bigint NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "ArchivedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RedundantFlowEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150122_InitialCreateV3') THEN
    CREATE UNIQUE INDEX "IX_FlowEntries_ClusterName_DstOwner_DstNs_SrcOwner_SrcNs_DstPo~" ON "FlowEntries" ("ClusterName", "DstOwner", "DstNs", "SrcOwner", "SrcNs", "DstPort");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150122_InitialCreateV3') THEN
    CREATE UNIQUE INDEX "IX_PossibleDropEntries_ClusterName_DstOwner_DstNs_SrcOwner_Src~" ON "PossibleDropEntries" ("ClusterName", "DstOwner", "DstNs", "SrcOwner", "SrcNs", "DstPort");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150122_InitialCreateV3') THEN
    CREATE UNIQUE INDEX "IX_RedundantFlowEntries_ClusterName_DstOwner_DstNs_SrcOwner_Sr~" ON "RedundantFlowEntries" ("ClusterName", "DstOwner", "DstNs", "SrcOwner", "SrcNs", "DstPort");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150122_InitialCreateV3') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260227150122_InitialCreateV3', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260309112053_EnrichedFlowsAdded') THEN
    CREATE TABLE "EnrichedFlowEntries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "FlowId" text NOT NULL,
        "FlowType" text NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "SourceCluster" text NOT NULL,
        "SourcePod" text NOT NULL,
        "SourceNamespace" text NOT NULL,
        "SourceOwner" text NOT NULL,
        "SourceOwnerType" text NOT NULL,
        "SourceNode" text NOT NULL,
        "SourceNodeIp" text NOT NULL,
        "SourcePodIp" text NOT NULL,
        "DestinationCluster" text NOT NULL,
        "DestinationPod" text NOT NULL,
        "DestinationNamespace" text NOT NULL,
        "DestinationOwner" text NOT NULL,
        "DestinationOwnerType" text NOT NULL,
        "DestinationNode" text NOT NULL,
        "DestinationNodeIp" text NOT NULL,
        "DestinationPodIp" text NOT NULL,
        "SourcePort" integer NOT NULL,
        "DestinationPort" integer NOT NULL,
        "Protocol" integer NOT NULL,
        "ProtocolName" text NOT NULL,
        "TcpFlags" integer NOT NULL,
        "TotalBytes" bigint NOT NULL,
        "TotalPackets" bigint NOT NULL,
        "EgressBytes" bigint NOT NULL,
        "IngressBytes" bigint NOT NULL,
        "EgressPackets" bigint NOT NULL,
        "IngressPackets" bigint NOT NULL,
        "EgressTimestamp" timestamp with time zone NOT NULL,
        "IngressTimestamp" timestamp with time zone NOT NULL,
        "CorrelationDeltaMs" double precision NOT NULL,
        "Description" text NOT NULL,
        "Route" text NOT NULL,
        "ServiceToService" text NOT NULL,
        "CorrelatedAt" timestamp with time zone NOT NULL,
        "CorrelationConfidence" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EnrichedFlowEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260309112053_EnrichedFlowsAdded') THEN
    CREATE UNIQUE INDEX "IX_EnrichedFlowEntries_FlowId" ON "EnrichedFlowEntries" ("FlowId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260309112053_EnrichedFlowsAdded') THEN
    CREATE INDEX "IX_EnrichedFlowEntries_SourceCluster_SourceOwner_DestinationCl~" ON "EnrichedFlowEntries" ("SourceCluster", "SourceOwner", "DestinationCluster", "DestinationOwner", "Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260309112053_EnrichedFlowsAdded') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260309112053_EnrichedFlowsAdded', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326071635_EnrichedFlowTableDropped') THEN
    DROP TABLE "EnrichedFlowEntries";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326071635_EnrichedFlowTableDropped') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260326071635_EnrichedFlowTableDropped', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326084346_CollectionsAdded') THEN
    DROP TABLE "RadarCollections";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326084346_CollectionsAdded') THEN
    CREATE TABLE "Collections" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "Clusters" jsonb NOT NULL,
        "Namespaces" jsonb NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Collections" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326084346_CollectionsAdded') THEN
    CREATE UNIQUE INDEX "IX_Collections_Name" ON "Collections" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326084346_CollectionsAdded') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260326084346_CollectionsAdded', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326095508_CollectionsLabelsAdded') THEN
    ALTER TABLE "Collections" ADD "Labels" jsonb NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326095508_CollectionsLabelsAdded') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260326095508_CollectionsLabelsAdded', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504091832_ExternalFlowAdded') THEN
    CREATE TABLE "ExternalFlowEntries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SrcClusterName" text NOT NULL,
        "DstClusterName" text NOT NULL,
        "DstIp" text NOT NULL,
        "DstOwner" text NOT NULL,
        "DstNs" text NOT NULL,
        "SrcOwner" text NOT NULL,
        "SrcNs" text NOT NULL,
        "DstPort" integer NOT NULL,
        "TcpFlags" integer NOT NULL,
        "Time" bigint NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ExternalFlowEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504091832_ExternalFlowAdded') THEN
    CREATE UNIQUE INDEX "IX_ExternalFlowEntries_SrcClusterName_DstClusterName_DstIp_Dst~" ON "ExternalFlowEntries" ("SrcClusterName", "DstClusterName", "DstIp", "DstOwner", "DstNs", "SrcOwner", "SrcNs", "DstPort");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504091832_ExternalFlowAdded') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260504091832_ExternalFlowAdded', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260525103517_RadarUpdated') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260525103517_RadarUpdated', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601120000_SubnetRulesAdded') THEN
    CREATE TABLE "SubnetRules" (
        "Id" uuid NOT NULL,
        "Cidr" text NOT NULL,
        "Label" text NOT NULL,
        "Description" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SubnetRules" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601120000_SubnetRulesAdded') THEN
    CREATE UNIQUE INDEX "IX_SubnetRules_Cidr" ON "SubnetRules" ("Cidr");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601120000_SubnetRulesAdded') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260601120000_SubnetRulesAdded', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601130000_DnsServersAdded') THEN
    CREATE TABLE "DnsServers" (
        "Id" uuid NOT NULL,
        "ClusterName" text NOT NULL,
        "Address" text NOT NULL,
        "Port" integer NOT NULL,
        "Description" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DnsServers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601130000_DnsServersAdded') THEN
    CREATE UNIQUE INDEX "IX_DnsServers_ClusterName_Address_Port" ON "DnsServers" ("ClusterName", "Address", "Port");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601130000_DnsServersAdded') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260601130000_DnsServersAdded', '10.0.7');
    END IF;
END $EF$;
COMMIT;

-- 20260603140000_FlowEntryVolumeAdded
-- Additive NDR volume/protocol columns (Bytes, Packets, Proto) on FlowEntries,
-- carried on the same topology topic. Not part of the unique key, defaulted to
-- 0 - existing rows and the upsert behaviour are unchanged (backward compatible).
START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603140000_FlowEntryVolumeAdded') THEN
    ALTER TABLE "FlowEntries" ADD COLUMN "Bytes" bigint NOT NULL DEFAULT 0;
    ALTER TABLE "FlowEntries" ADD COLUMN "Packets" bigint NOT NULL DEFAULT 0;
    ALTER TABLE "FlowEntries" ADD COLUMN "Proto" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603140000_FlowEntryVolumeAdded') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603140000_FlowEntryVolumeAdded', '10.0.7');
    END IF;
END $EF$;
COMMIT;

-- 20260603150000_ExternalFlowEntryVolumeAdded
-- Same additive volume/protocol columns on ExternalFlowEntries, mirroring
-- FlowEntries. Defaulted to 0, not in the unique key - backward compatible.
START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603150000_ExternalFlowEntryVolumeAdded') THEN
    ALTER TABLE "ExternalFlowEntries" ADD COLUMN "Bytes" bigint NOT NULL DEFAULT 0;
    ALTER TABLE "ExternalFlowEntries" ADD COLUMN "Packets" bigint NOT NULL DEFAULT 0;
    ALTER TABLE "ExternalFlowEntries" ADD COLUMN "Proto" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603150000_ExternalFlowEntryVolumeAdded') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603150000_ExternalFlowEntryVolumeAdded', '10.0.7');
    END IF;
END $EF$;
COMMIT;

-- 20260603160000_FlowVolumeBucketRollup
-- Moves NDR volume from the topology edge tables to a proper time-series: drops
-- the last-write-wins Bytes/Packets from FlowEntries/ExternalFlowEntries (Proto
-- stays - stable per edge) and creates FlowVolumeBuckets, one pre-aggregated row
-- per (entity, window, external). Bounded cardinality, TTL-pruned.
START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603160000_FlowVolumeBucketRollup') THEN
    ALTER TABLE "FlowEntries" DROP COLUMN "Bytes";
    ALTER TABLE "FlowEntries" DROP COLUMN "Packets";
    ALTER TABLE "ExternalFlowEntries" DROP COLUMN "Bytes";
    ALTER TABLE "ExternalFlowEntries" DROP COLUMN "Packets";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603160000_FlowVolumeBucketRollup') THEN
    CREATE TABLE "FlowVolumeBuckets" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ClusterName" text NOT NULL,
        "Namespace" text NOT NULL,
        "Workload" text NOT NULL,
        "IsExternal" boolean NOT NULL,
        "WindowStart" timestamp with time zone NOT NULL,
        "Bytes" bigint NOT NULL,
        "Packets" bigint NOT NULL,
        "FlowCount" bigint NOT NULL,
        "DistinctDst" integer NOT NULL,
        "DistinctPorts" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FlowVolumeBuckets" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603160000_FlowVolumeBucketRollup') THEN
    CREATE INDEX "IX_FlowVolumeBuckets_ClusterName_Namespace_Workload_WindowStart" ON "FlowVolumeBuckets" ("ClusterName", "Namespace", "Workload", "WindowStart");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603160000_FlowVolumeBucketRollup') THEN
    CREATE INDEX "IX_FlowVolumeBuckets_WindowStart" ON "FlowVolumeBuckets" ("WindowStart");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603160000_FlowVolumeBucketRollup') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603160000_FlowVolumeBucketRollup', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612073938_TetragonAdded') THEN
    CREATE TABLE "ProcessFlowEntries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ClusterName" text NOT NULL,
        "Namespace" text NOT NULL,
        "Workload" text NOT NULL,
        "Binary" text NOT NULL,
        "DstNs" text NOT NULL,
        "DstOwner" text NOT NULL,
        "DstPort" integer NOT NULL,
        "Proto" integer NOT NULL,
        "Args" text NOT NULL,
        "PodName" text NOT NULL,
        "ContainerName" text NOT NULL,
        "NodeName" text NOT NULL,
        "Pid" integer NOT NULL,
        "Ppid" integer NOT NULL,
        "Uid" bigint NOT NULL,
        "ExecId" text NOT NULL,
        "Confidence" text NOT NULL,
        "DeltaMs" integer NOT NULL,
        "ConnectTimeMs" bigint NOT NULL,
        "FlowTimeMs" bigint NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ProcessFlowEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612073938_TetragonAdded') THEN
    CREATE UNIQUE INDEX "IX_ProcessFlowEntries_ClusterName_Namespace_Workload_Binary_Ds~" ON "ProcessFlowEntries" ("ClusterName", "Namespace", "Workload", "Binary", "DstNs", "DstOwner", "DstPort");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612073938_TetragonAdded') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260612073938_TetragonAdded', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617071146_ProcessPolicyRecordsAdded') THEN
    CREATE TABLE "ProcessPolicyRecords" (
        "Id" uuid NOT NULL,
        "ClusterName" text NOT NULL,
        "Namespace" text NOT NULL,
        "Workload" text NOT NULL,
        "Style" text NOT NULL,
        "Stage" text NOT NULL,
        "Status" text NOT NULL,
        "Name" text NOT NULL,
        "Yaml" text NOT NULL,
        "PodSelector" text NOT NULL,
        "AllowBinaries" jsonb NOT NULL,
        "AllowPorts" jsonb NOT NULL,
        "WouldBlockNow" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "AppliedAt" timestamp with time zone,
        "LastError" text,
        CONSTRAINT "PK_ProcessPolicyRecords" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617071146_ProcessPolicyRecordsAdded') THEN
    CREATE UNIQUE INDEX "IX_ProcessPolicyRecords_ClusterName_Namespace_Workload_Style" ON "ProcessPolicyRecords" ("ClusterName", "Namespace", "Workload", "Style");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617071146_ProcessPolicyRecordsAdded') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260617071146_ProcessPolicyRecordsAdded', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617102813_ProcessPolicyRecordsUpdated') THEN
    ALTER TABLE "ProcessPolicyRecords" ADD "EnforceAction" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617102813_ProcessPolicyRecordsUpdated') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260617102813_ProcessPolicyRecordsUpdated', '10.0.7');
    END IF;
END $EF$;
COMMIT;
