apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy
    {{- include "axera.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: proxy }
  template:
    metadata:
      labels: { app: proxy }
    spec:
      serviceAccountName: axera-sa
      {{- $waited := include "axera.waitForDb" . }}
      {{- if $waited }}
      initContainers:
        {{- $waited | nindent 8 }}
      {{- end }}
      containers:
        - name: proxy
          image: {{ include "axera.image" (dict "img" .Values.images.proxy "ctx" .) }}
          imagePullPolicy: Always
          ports:
            - { containerPort: 8080 }
          envFrom:
            - configMapRef: { name: axera-app-config }
            - secretRef: { name: axera-app-secret }
          env:
            - { name: ASPNETCORE_ENVIRONMENT, value: Production }
            - { name: ASPNETCORE_URLS, value: "http://+:8080" }
            - name: ConnectionStrings__DefaultConnection
              valueFrom: { secretKeyRef: { name: axera-db-secrets, key: APP_DB_CONNSTR } }
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: {{ .Values.global.namespace }}
  labels: {{- include "axera.labels" . | nindent 4 }}
spec:
  selector: { app: proxy }
  ports:
    - { name: http, port: 8080, targetPort: 8080 }
